spring:
  datasource:
    url: jdbc:mysql://localhost:3306/collawork?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: gangnam
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  logging:
    level:
      org.springframework.security: DEBUG
      org.springframework.web: DEBUG

  server:
    error:
      whitelabel:
        enabled: false


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 513947071243-9q3t9drntphf297pvojlktogpvua4tad.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            client-authentication-method: post
            authorization-grant-type: authorization_code
            provider: google

          kakao:
            client-id: f851b2331a5966daafc3644d19ed1b77
            scope: profile
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            client-authentication-method: post
            authorization-grant-type: authorization_code
            provider: kakao

          naver:
            client-id: IBhJHFFQ0L0ZWvyW0IUQ
            client-secret: aFV3IPKHcQ
            scope: profile
            redirect-uri: "{baseUrl}/login/oauth2/code/naver"
            client-authentication-method: post
            authorization-grant-type: authorization_code
            provider: naver

        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: id

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB   # 파일 하나의 최대 크기
      max-request-size: 10MB # 전체 요청의 최대 크기

  web:
    resources:
      static-locations: "classpath:/static/,file:uploads/"  # 새로운 정적 리소스 경로 설정

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.collawork.back.model

jwt:
  secret: Czy43Z6YL4xPDc6pmytWKLle6oQtdFPKQWKNAKhWvhQMLzZlyazjs+hB05JymnK0LdnmBj+88AOW6RQ0j1NzIg==
  expiration: 86400000

